### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by christophehurpeau** [DavisDevelopment/Tum-Tum#1]
How to use it ?

Thanks

**Comment by DavisDevelopment** [comment]
Let me get back to you on that, bro :P Been a while since this project was active.

**Comment by DavisDevelopment** [comment]
Honestly, this version was never stable, it seems. Path resolution was broken, along with other issues. A rewrite will occur soon, but until then, I'd recommend using browserify, along with uglifyjs. You'll come to about the same result.

**Comment by christophehurpeau** [comment]
Okay, thanks
